services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: sentiment_backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./mlruns:/app/mlruns
      - ./src:/app/src
    environment:
      - TOKENIZERS_PARALLELISM=false
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mlflow
  
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    container_name: sentiment_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    depends_on:
      - backend

  mlflow:
    image: arungudvil/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts
    volumes:
      - ./mlruns:/mlflow/artifacts

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - backend

volumes:
  grafana_data: