apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nicoaryaa/sentra-backend:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc