apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: arungudvil/mlflow:latest
        ports:
        - containerPort: 5000
        command:
        - sh
        - -c
        - |
          mkdir -p /mlflow && \
          mlflow server --host 0.0.0.0 --port 5000 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root file:///mlflow
        volumeMounts:
        - name: mlflow-data
          mountPath: /mlflow
      volumes:
      - name: mlflow-data
        persistentVolumeClaim:
          claimName: data-pvc