name: CI/CD Pipeline for Sentiment Analysis App

on:
  push:
    branches:
      - main

env:
  IMAGE_BACKEND: nicoaryaa/sentiment-backend
  IMAGE_FRONTEND: nicoaryaa/sentiment-frontend
  TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 🔹 Checkout kode
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🔹 Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🔹 Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🔹 Build & Push Backend Image
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: ${{ env.IMAGE_BACKEND }}:${{ env.TAG }}

      # 🔹 Build & Push Frontend Image
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.frontend
          push: true
          tags: ${{ env.IMAGE_FRONTEND }}:${{ env.TAG }}

      # 🔹 Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/ $(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt )/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # 🔹 Setup kubeconfig
      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ~/.kube/config

      # 🔹 Deploy ke Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment/backend || true
          kubectl rollout restart deployment/frontend || true
          kubectl rollout status deployment/backend
          kubectl rollout status deployment/frontend

      # 🔹 Verifikasi Pod
      - name: Check Pods
        run: |
          kubectl get pods
          kubectl get services